<?php
/**
 * Element: select kraju nabywcy (ISO 3166-1 alpha-2) z select2
 *
 * Zmienne:
 *   $fieldName  — nazwa pola HTML, domyślnie 'invoice_contractor[country]'
 *   $value      — bieżąca wartość, domyślnie 'PL'
 *   $label      — etykieta, domyślnie 'Kraj'
 *   $selectId   — id elementu, domyślnie 'contractor-country-select'
 */
$fieldName = $fieldName ?? 'invoice_contractor[country]';
$value     = $value     ?? 'PL';
$label     = $label     ?? 'Kraj';
$selectId  = $selectId  ?? 'contractor-country-select';

$countries = [
    'AF' => 'AF — Afganistan',
    'AL' => 'AL — Albania',
    'DZ' => 'DZ — Algieria',
    'AD' => 'AD — Andora',
    'AO' => 'AO — Angola',
    'AG' => 'AG — Antigua i Barbuda',
    'SA' => 'SA — Arabia Saudyjska',
    'AR' => 'AR — Argentyna',
    'AM' => 'AM — Armenia',
    'AU' => 'AU — Australia',
    'AT' => 'AT — Austria',
    'AZ' => 'AZ — Azerbejdżan',
    'BS' => 'BS — Bahamy',
    'BH' => 'BH — Bahrajn',
    'BD' => 'BD — Bangladesz',
    'BB' => 'BB — Barbados',
    'BE' => 'BE — Belgia',
    'BZ' => 'BZ — Belize',
    'BJ' => 'BJ — Benin',
    'BT' => 'BT — Bhutan',
    'BY' => 'BY — Białoruś',
    'BO' => 'BO — Boliwia',
    'BA' => 'BA — Bośnia i Hercegowina',
    'BW' => 'BW — Botswana',
    'BR' => 'BR — Brazylia',
    'BN' => 'BN — Brunei',
    'BG' => 'BG — Bułgaria',
    'BF' => 'BF — Burkina Faso',
    'BI' => 'BI — Burundi',
    'CL' => 'CL — Chile',
    'CN' => 'CN — Chiny',
    'HR' => 'HR — Chorwacja',
    'CY' => 'CY — Cypr',
    'TD' => 'TD — Czad',
    'ME' => 'ME — Czarnogóra',
    'CZ' => 'CZ — Czechy',
    'DK' => 'DK — Dania',
    'CD' => 'CD — Demokratyczna Republika Konga',
    'DJ' => 'DJ — Dżibuti',
    'DM' => 'DM — Dominika',
    'DO' => 'DO — Dominikana',
    'EG' => 'EG — Egipt',
    'EC' => 'EC — Ekwador',
    'ER' => 'ER — Erytrea',
    'EE' => 'EE — Estonia',
    'ET' => 'ET — Etiopia',
    'FJ' => 'FJ — Fidżi',
    'PH' => 'PH — Filipiny',
    'FI' => 'FI — Finlandia',
    'FR' => 'FR — Francja',
    'GA' => 'GA — Gabon',
    'GM' => 'GM — Gambia',
    'GH' => 'GH — Ghana',
    'GR' => 'GR — Grecja',
    'GD' => 'GD — Grenada',
    'GE' => 'GE — Gruzja',
    'GY' => 'GY — Gujana',
    'GT' => 'GT — Gwatemala',
    'GN' => 'GN — Gwinea',
    'GW' => 'GW — Gwinea Bissau',
    'GQ' => 'GQ — Gwinea Równikowa',
    'HT' => 'HT — Haiti',
    'ES' => 'ES — Hiszpania',
    'HN' => 'HN — Honduras',
    'IN' => 'IN — Indie',
    'ID' => 'ID — Indonezja',
    'IQ' => 'IQ — Irak',
    'IR' => 'IR — Iran',
    'IE' => 'IE — Irlandia',
    'IS' => 'IS — Islandia',
    'IL' => 'IL — Izrael',
    'JM' => 'JM — Jamajka',
    'JP' => 'JP — Japonia',
    'YE' => 'YE — Jemen',
    'JO' => 'JO — Jordania',
    'KH' => 'KH — Kambodża',
    'CM' => 'CM — Kamerun',
    'CA' => 'CA — Kanada',
    'QA' => 'QA — Katar',
    'KZ' => 'KZ — Kazachstan',
    'KE' => 'KE — Kenia',
    'KG' => 'KG — Kirgistan',
    'KI' => 'KI — Kiribati',
    'CO' => 'CO — Kolumbia',
    'KM' => 'KM — Komory',
    'CG' => 'CG — Kongo',
    'KP' => 'KP — Korea Północna',
    'KR' => 'KR — Korea Południowa',
    'KW' => 'KW — Kuwejt',
    'LA' => 'LA — Laos',
    'LS' => 'LS — Lesotho',
    'LB' => 'LB — Liban',
    'LR' => 'LR — Liberia',
    'LY' => 'LY — Libia',
    'LI' => 'LI — Liechtenstein',
    'LT' => 'LT — Litwa',
    'LU' => 'LU — Luksemburg',
    'LV' => 'LV — Łotwa',
    'MK' => 'MK — Macedonia Północna',
    'MG' => 'MG — Madagaskar',
    'MW' => 'MW — Malawi',
    'MV' => 'MV — Malediwy',
    'MY' => 'MY — Malezja',
    'ML' => 'ML — Mali',
    'MT' => 'MT — Malta',
    'MA' => 'MA — Maroko',
    'MR' => 'MR — Mauretania',
    'MU' => 'MU — Mauritius',
    'MX' => 'MX — Meksyk',
    'FM' => 'FM — Mikronezja',
    'MD' => 'MD — Mołdawia',
    'MC' => 'MC — Monako',
    'MN' => 'MN — Mongolia',
    'MZ' => 'MZ — Mozambik',
    'MM' => 'MM — Myanmar',
    'NA' => 'NA — Namibia',
    'NR' => 'NR — Nauru',
    'NP' => 'NP — Nepal',
    'NL' => 'NL — Niderlandy',
    'DE' => 'DE — Niemcy',
    'NE' => 'NE — Niger',
    'NG' => 'NG — Nigeria',
    'NI' => 'NI — Nikaragua',
    'NO' => 'NO — Norwegia',
    'NZ' => 'NZ — Nowa Zelandia',
    'OM' => 'OM — Oman',
    'PK' => 'PK — Pakistan',
    'PW' => 'PW — Palau',
    'PA' => 'PA — Panama',
    'PG' => 'PG — Papua Nowa Gwinea',
    'PY' => 'PY — Paragwaj',
    'PE' => 'PE — Peru',
    'PL' => 'PL — Polska',
    'PT' => 'PT — Portugalia',
    'ZA' => 'ZA — Republika Południowej Afryki',
    'CF' => 'CF — Republika Środkowoafrykańska',
    'RU' => 'RU — Rosja',
    'RO' => 'RO — Rumunia',
    'RW' => 'RW — Rwanda',
    'WS' => 'WS — Samoa',
    'SM' => 'SM — San Marino',
    'SN' => 'SN — Senegal',
    'RS' => 'RS — Serbia',
    'SC' => 'SC — Seszele',
    'SL' => 'SL — Sierra Leone',
    'SG' => 'SG — Singapur',
    'SK' => 'SK — Słowacja',
    'SI' => 'SI — Słowenia',
    'SO' => 'SO — Somalia',
    'LK' => 'LK — Sri Lanka',
    'US' => 'US — Stany Zjednoczone',
    'SZ' => 'SZ — Eswatini',
    'SD' => 'SD — Sudan',
    'SS' => 'SS — Sudan Południowy',
    'SR' => 'SR — Surinam',
    'SY' => 'SY — Syria',
    'CH' => 'CH — Szwajcaria',
    'SE' => 'SE — Szwecja',
    'TJ' => 'TJ — Tadżykistan',
    'TH' => 'TH — Tajlandia',
    'TZ' => 'TZ — Tanzania',
    'TL' => 'TL — Timor Wschodni',
    'TG' => 'TG — Togo',
    'TO' => 'TO — Tonga',
    'TT' => 'TT — Trynidad i Tobago',
    'TN' => 'TN — Tunezja',
    'TR' => 'TR — Turcja',
    'TM' => 'TM — Turkmenistan',
    'TV' => 'TV — Tuvalu',
    'UG' => 'UG — Uganda',
    'UA' => 'UA — Ukraina',
    'UY' => 'UY — Urugwaj',
    'UZ' => 'UZ — Uzbekistan',
    'VU' => 'VU — Vanuatu',
    'VE' => 'VE — Wenezuela',
    'HU' => 'HU — Węgry',
    'GB' => 'GB — Wielka Brytania',
    'VN' => 'VN — Wietnam',
    'IT' => 'IT — Włochy',
    'CI' => 'CI — Wybrzeże Kości Słoniowej',
    'XI' => 'XI — Irlandia Północna (XI)',
    'ZM' => 'ZM — Zambia',
    'ZW' => 'ZW — Zimbabwe',
    'AE' => 'AE — Zjednoczone Emiraty Arabskie',
];
?>
<label class="form-label" for="<?= h($selectId) ?>"><?= h($label) ?></label>
<select class="form-select contractor-country-select" id="<?= h($selectId) ?>" name="<?= h($fieldName) ?>">
<?php foreach ($countries as $code => $name): ?>
  <option value="<?= h($code) ?>"<?= $value === $code ? ' selected' : '' ?>><?= h($name) ?></option>
<?php endforeach; ?>
</select>
<script>
(function(){
  var id = <?= json_encode($selectId) ?>;
  function init(){ if (window.$ && $.fn && $.fn.select2) { $('#'+id).select2({ width: '100%', allowClear: false, language: { searching: function(){ return 'Szukam…'; }, noResults: function(){ return 'Brak wyników'; } } }); } }
  if (document.readyState === 'loading') { document.addEventListener('DOMContentLoaded', init); } else { init(); }
})();
</script>
